name: flutter_advanced
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # State Management
  flutter_bloc: ^8.1.6
  # Code generator with cubit(bloc)
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  # Generate code Json
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  # DI
  get_it: ^8.0.2
  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.4
  # Localization
  easy_localization: ^3.0.7
  intl: ^0.19.0
  # UI
  flutter_svg: ^2.0.11
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.2 # responsive screen

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^5.0.0

# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # the material Icons class.
  uses-material-design: true
